// Generated by CoffeeScript 1.3.3
(function() {
  var MuzebraPlugin;

  MuzebraPlugin = (function() {

    function MuzebraPlugin() {
      this.id = "muzebra_plugin";
      return this.init();
    }

    MuzebraPlugin.prototype.init = function() {
      console.log("muzebra plugin inited");
      return true;
    };

    MuzebraPlugin.prototype.query = function(query, callback) {
      var url,
        _this = this;
      url = "http://muzebra.com/search/?q=" + encodeURIComponent(query);
      return $.get(url, function(data) {
        var dur, i, name, re, res;
        re = /<a class="info".+?data-link="(.+?)".+?data-duration="(.+?)">(.+?)<\/a>/gim;
        data = data.replace(/[\n\t\r]/gm, "");
        res = re.exec(data);
        _this.songs = [];
        i = 0;
        while (res !== null) {
          if (res[1].indexOf("http") !== -1) {
            name = res[3].split(" - ");
            dur = _this.secondsToString(res[2]);
            _this.songs[i] = new Track(name[1], name[0], dur, res[1], _this.id);
          }
          res = re.exec(data);
          i++;
        }
        callback(_this.songs);
        return true;
      });
    };

    MuzebraPlugin.prototype.secondsToString = function(totalseconds) {
      var mins, secs, time;
      totalseconds = parseInt(totalseconds);
      mins = Math.floor(totalseconds / 60);
      secs = totalseconds - mins * 60;
      time = mins < 10 ? "0" + mins : "" + mins;
      time += ":";
      time += secs < 10 ? "0" + secs : "" + secs;
      return time;
    };

    MuzebraPlugin.prototype.getStreamUrl = function(url, callback) {
      return $.post("http://muzebra.com/service/user/playerparams/", {}, function(data) {
        data = $.parseJSON(data);
        url = "http://savestreaming.com/t/" + url + "_" + data.hash + "/";
        callback(url);
        return true;
      });
    };

    return MuzebraPlugin;

  })();

  window.plugins.push(new MuzebraPlugin());

}).call(this);
