// Generated by CoffeeScript 1.3.3
(function() {
  var TestPlugin;

  TestPlugin = (function() {

    function TestPlugin() {
      console.log("plugin inited");
    }

    TestPlugin.prototype.query = function(query) {
      var url;
      this.query = query;
      url = "http://ololo.fm/search/?x=0&y=0&query=" + encodeURIComponent(this.query);
      return $.get(url, function(data) {
        var i, re, res, songs;
        console.log(data);
        re = /<a href="\/song\/(.+?)".+?<span>(.+?)<\/span><br.*?\/>(.+?)<\/a><dfn>(.+?)<\/dfn>/gim;
        data = data.replace(/[\n\t\r]/gm, "");
        res = re.exec(data);
        songs = [];
        i = 0;
        while (res !== null) {
          songs[i] = {
            "title": res[2],
            "aritst": res[3],
            "time": res[4],
            "url": "http://ololo.fm/save/" + res[1]
          };
          res = re.exec(data);
          i++;
        }
        return console.log(songs);
      });
    };

    return TestPlugin;

  })();

  window.plugins.push(new TestPlugin());

}).call(this);
