// Generated by CoffeeScript 1.3.3
(function() {
  var Discogs;

  Discogs = (function() {
    var searchUrlBase;

    searchUrlBase = "http://api.discogs.com/database/search";

    function Discogs() {}

    Discogs.prototype.search = function(query, callback) {
      var url;
      url = searchUrlBase + "?q=" + encodeURI(query);
      return $.getJSON(url, function(data) {
        var res, results, _i, _len, _ref;
        results = [];
        _ref = data.results;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          res = _ref[_i];
          switch (res.type) {
            case 'artist':
              results.push(new Artist(res.id, res.title, res.thumb));
              break;
            case 'master':
            case 'release':
              results.push(new Album(res.id, res.title, res.thumb, res.year, res.country, res.style, res.genre));
          }
        }
        return callback(results);
      });
    };

    return Discogs;

  })();

  window.Discogs = Discogs;

}).call(this);
